### ISSUE TITLE
[Android Bootcamp] Project 0: Todo - Ready for Review

### ISSUE THREAD

**Issue by mykola-tarchanyn** [mikolasw/Simple-To-Do#1]
My app is complete, please review @codepathreview @codepath

Sorry for mess with gif file :)

**Comment by nesquena** [comment]
Hi Mykola,

Looks good, this exercise is intended in part to give you an introduction to the general rhythm of this course. The course is entirely project-based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer  learn the practical elements of Android development and best practices as quickly as possible.

I wanted to let you know that unfortunately the class is already nearing full at this point, but we are happy to add you to the course waitlist. We will be determining final admittance into the program over the next 2 weeks. For those not admitted as participants, we can also offer access to applicants as a remote observer cohort that has access to the materials and is able to work on the projects at their own pace.

Hope you enjoyed working on the pre-work so far. You are definitely encouraged to continue working on this project now that you've hit the initial pre-work deadline. We'll be following up again with you soon.

**Comment by mykola-tarchanyn** [comment]
Hello,

Thank you for you response. Actually I dont need any training or something
like this, only one reason that I've done this test is I WANT TO WORK IN
UBER :) . I was trying to do all my best in this project, but unfortunately
something wasn't so good. If you can give me some feedback of what wasn't
so good, please do it. It will really help me in a future . Again, thank
you!

Mykola

**Comment by nesquena** [comment]
Hi Mykola,

Appreciate your interest in working at Uber :) Your project contains a few optionals and is fine. We have received a large number of pre-works (200+) to fit into 30 in-person and 30 remote so we are in the difficult position of having to make tough choices. Hope you enjoyed the project and we will be in touch again soon to follow up again.
